USE training_db;

CREATE TABLE employees(
  id INT NOT NULL AUTO_INCREMENT,
  staff_id VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  joined_at DATE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);